
version: '3.8'
services:
  redis:
    image: redis:7
    container_name: redis_memory
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./data/backups:/data
    command: redis-server --appendonly yes

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniopass
    volumes:
      - ./data/minio:/data
    ports:
      - "${MINIO_PORT}:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"

  api:
    build: ./src/api
    container_name: memory_api
    ports:
      - "${API_PORT}:8080"
    env_file:
      - ./config/.env
    volumes:
      - ./data:/app/data
